### ISSUE TITLE
Umm... You copied.

### ISSUE THREAD

**Issue by legoboy0215** [deathcrow999/LWTAuth#1]
You copied from ServerAuth. You can be DMCAed.

**Comment by deathcrow999** [comment]
This is not one of my projects i did not create this??

**Comment by legoboy0215** [comment]
??? What do you mean. But this is copied.

**Comment by deathcrow999** [comment]
I mean i did not create this repository or project the only project ive been working on is KillBlock

**Comment by legoboy0215** [comment]
then who did.

**Comment by deathcrow999** [comment]
I have two team members but ive never know them to copy anyones work can u provide proof that this is copied?

**Comment by deathcrow999** [comment]
If so i will remove it

**Comment by legoboy0215** [comment]
See the command. It has serverauth.

**Comment by legoboy0215** [comment]
https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/src/ServerAuth/ServerAuth.php

**Comment by deathcrow999** [comment]
Okay i will remove it thx for telling me
